### ISSUE TITLE
hopper into item causes crash

### ISSUE THREAD

**Issue by Monster-Zer0** [AlexIIL/LibBlockAttributes#34]
I was forwarded here from the kibe mod. it appears that my issue could most likely be lib block attributes.

https://hastebin.com/aqujiqatub.coffeescript

tried to put a hopper on a block (big torch in kibe), tried to feed torches into it.. crash.

**Comment by flier268** [comment]
> 
> 
> I was forwarded here from the kibe mod. it appears that my issue could most likely be lib block attributes.
> 
> https://hastebin.com/aqujiqatub.coffeescript
> 
> tried to put a hopper on a block (big torch in kibe), tried to feed torches into it.. crash.
I think your issue is this.
https://github.com/lucaargolo/kibe/issues/25


But I had same issue
I had another crash but this,
![圖片](https://user-images.githubusercontent.com/19989232/102306246-bf306500-3f9c-11eb-841d-f11d35f69bc3.png)
After the lever turn off, server will crash
[crash-log](https://pastebin.com/FkYFwtXU)

**Comment by flier268** [comment]
![圖片](https://user-images.githubusercontent.com/19989232/102306634-a5435200-3f9d-11eb-9b6f-07c32884aaad.png)
This will cause crash too,
But [Block being ticked] is upper dropper

**Comment by AlexIIL** [comment]
Ok, this should not be fixed in [0.8.5](https://alexiil.uk/maven/alexiil/mc/lib/libblockattributes-all/0.8.5/libblockattributes-all-0.8.5.jar). To be honest I'm not sure if the original crash has been fixed by this, but the report has expired so I have no idea.

**Comment by flier268** [comment]
Yes, it fixed.

**Comment by AlexIIL** [comment]
Thanks!
